parameters:
    dmitxe_blog.listener.article_author.class: SmartCore\Bundle\BlogBundle\EventListener\ArticleAuthorListener
    dmitxe_blog.model.article.class: Dmitxe\BlogBundle\Entity\Article

services:
    dmitxe_blog.listener.article_author:
        class: %dmitxe_blog.listener.article_author.class%
        arguments: [@security.context, @logger]
        tags:
            - { name: kernel.event_subscriber }

    dmitxe_blog.listener.article_image:
        class: Dmitxe\BlogBundle\EventListener\ImageArticleListener
        arguments: [@smart_media_collection]
        tags:
            - { name: kernel.event_subscriber }

    dmitxe_blog.article.edit.form.type:
        class: Dmitxe\BlogBundle\Form\Type\ArticleEditFormType
        arguments: [%dmitxe_blog.model.article.class%]
