mremi_contact_form:
    path: /contact/
    defaults: { _controller: MremiContactBundle:Contact:index }

mremi_contact_confirmation:
    path: /contact/confirmation/
    defaults: { _controller: MremiContactBundle:Contact:confirm }
