mremi_contact_form:
    path: /contacts/
    defaults: { _controller: DmitxeContactBundle:Contact:index }

mremi_contact_confirmation:
    path: /contacts/confirmation/
    defaults: { _controller: DmitxeContactBundle:Contact:confirm }
