dmitxe_site_index:
    path: /
    defaults: { _controller: DmitxeSiteBundle:Page:index }

dmitxe_site_admin:
    path: /admin/
    defaults: { _controller: DmitxeSiteBundle:Admin:index }

dmitxe_site_about:
    path: /about/
    defaults: { _controller: DmitxeSiteBundle:Page:about }

smart_blog_admin_index:
    path:   /admin/blog/
    defaults: { _controller: DmitxeSiteBundle:Admin:adminBlog }
