dmitxe_site_admin:
    path: /admin/
    defaults: { _controller: DmitxeSiteBundle:Admin:index }

dmitxe_site_about:
    path: /about/
    defaults: { _controller: DmitxeSiteBundle:Page:about }

smart_blog_admin_index:
    path:   /admin/blog/
    defaults: { _controller: DmitxeSiteBundle:Admin:adminBlog }

dmitxe_sitemap_xml: # @todo судя по всему этот маршрут и контроллер ненужен т.к. сделан внешний паук.
    path: /sitemap.xml
    defaults: { _controller: DmitxeSiteBundle:Sitemap:xml, _format: xml }
    requirements: { _format: (xml), _method: GET }

dmitxe_sitemap_html:
    path: /sitemap/
    defaults: { _controller: DmitxeSiteBundle:Sitemap:html }
