parameters:
#    dmitxe_site.example.class: Dmitxe\SiteBundle\Example

services:
    # Menu selected items
    dmitxe_site.menu.voter.request:
        class: Dmitxe\SiteBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
