fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

dmitxe_demo:
    resource: "@DmitxeDemoBundle/Resources/config/routing.yml"

smart_media:
    resource: "@SmartMediaBundle/Resources/config/routing.yml"

dmitxe_site:
    resource: "@DmitxeSiteBundle/Resources/config/routing.yml"

smart_blog_admin_article:
    resource: "@SmartBlogBundle/Resources/config/routing_admin_article.yml"
    prefix:   /admin/blog/article/

smart_blog_admin_category:
    resource: "@SmartBlogBundle/Resources/config/routing_admin_category.yml"
    prefix:   /admin/blog/category/

smart_blog_admin_tag:
    resource: "@SmartBlogBundle/Resources/config/routing_admin_tag.yml"
    prefix:   /admin/blog/tag/

smart_texter:
    resource: "@SmartTexterBundle/Resources/config/routing_admin.yml"
    prefix:   /admin/texter/

dmitxe_blog:
    resource: "@DmitxeBlogBundle/Resources/config/routing.yml"
    prefix:   /blog/

dmitxe_news:
    resource: "@DmitxeNewsBundle/Resources/config/routing.yml"
    prefix:   /news/

dmitxe_news_admin:
    resource: "@DmitxeNewsBundle/Resources/config/routing_admin.yml"
    prefix:   /admin/news/

smart_gallery:
    resource: "@SmartGalleryBundle/Resources/config/routing.yml"
    prefix:   /gallery/

dmitxe_user:
    resource: "@DmitxeUserBundle/Resources/config/routing.yml"

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

mremi_contact_form:
    resource: "@DmitxeContactBundle/Resources/config/routing.yml"
