services:
    dmitxe_news.article:
        class: SmartCore\Bundle\BlogBundle\Service\ArticleService
        arguments:
            - @doctrine.orm.default_entity_manager
            - @dmitxe_news.article.repository
            - @dmitxe_news.cache
            - @event_dispatcher
            - %smart_blog.items_per_page%

    dmitxe_news.tag:
        class: SmartCore\Bundle\BlogBundle\Service\TagService
        arguments:
            - @doctrine.orm.default_entity_manager
            - @dmitxe_news.article.repository
            - @dmitxe_news.cache
            - @dmitxe_news.tag.repository
            - @event_dispatcher
            - @router
            - %smart_blog.items_per_page%

    dmitxe_news.cache: # @todo настройку через конфиг.
        alias: liip_doctrine_cache.ns.dmitxe_news

    dmitxe_news.article.repository:
        class:           SmartCore\Bundle\BlogBundle\Repository\ArticleRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:       ['Dmitxe\NewsBundle\Entity\Article']

    dmitxe_news.tag.repository:
        class:           SmartCore\Bundle\BlogBundle\Repository\TagRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:       ['Dmitxe\NewsBundle\Entity\Tag']
