parameters:
    dmitxe_news.model.article.class: Dmitxe\NewsBundle\Entity\Article
    dmitxe_news.model.tag.class: Dmitxe\NewsBundle\Entity\Tag

services:
    dmitxe_news.article:
        class: SmartCore\Bundle\BlogBundle\Service\ArticleService
        arguments:
            - @doctrine.orm.default_entity_manager
            - @dmitxe_news.article.repository
            - @dmitxe_news.cache
            - @event_dispatcher
            - %smart_blog.items_per_page%

    dmitxe_news.tag:
        class: SmartCore\Bundle\BlogBundle\Service\TagService
        arguments:
            - @doctrine.orm.default_entity_manager
            - @dmitxe_news.article.repository
            - @dmitxe_news.cache
            - @dmitxe_news.tag.repository
            - @event_dispatcher
            - @router
            - %smart_blog.items_per_page%

    dmitxe_news.cache: # @todo настройку через конфиг.
        alias: liip_doctrine_cache.ns.dmitxe_news

    dmitxe_news.article.create.form.type:
        class: SmartCore\Bundle\BlogBundle\Form\Type\ArticleCreateFormType
        arguments: [%dmitxe_news.model.article.class%]

    dmitxe_news.article.edit.form.type:
        class: SmartCore\Bundle\BlogBundle\Form\Type\ArticleEditFormType
        arguments: [%dmitxe_news.model.article.class%]

    dmitxe_news.tag.create.form.type:
        class: SmartCore\Bundle\BlogBundle\Form\Type\TagCreateFormType
        arguments: [%dmitxe_news.model.tag.class%]

    dmitxe_news.tag.edit.form.type:
        class: SmartCore\Bundle\BlogBundle\Form\Type\TagEditFormType
        arguments: [%dmitxe_news.model.tag.class%]

    dmitxe_news.article.repository:
        class:           SmartCore\Bundle\BlogBundle\Repository\ArticleRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:       [%dmitxe_news.model.article.class%]

    dmitxe_news.tag.repository:
        class:           SmartCore\Bundle\BlogBundle\Repository\TagRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:       [%dmitxe_news.model.tag.class%]
