parameters:
#    smart_social.example.class: SmartCore\Bundle\SocialBundle\Example

services:
#    smart_social.example:
#        class: %smart_social.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
