smart_blog.article.index:
    path: /
    defaults: { _controller: SmartBlogBundle:Article:index }

smart_blog.article.index.page_1_redirect_TO_index:
    path: /page/
    defaults: { _controller: SmartBlogBundle:Article:index, page: 1 }

smart_blog.article.index.page:
    path: /page/{page}/
    defaults: { _controller: SmartBlogBundle:Article:index }

smart_blog.article.show:
    path: /{slug}.html
    defaults: { _controller: SmartBlogBundle:Article:show }

smart_blog.article.create:
    path: /create/
    defaults: { _controller: SmartBlogBundle:Article:create }

smart_blog.article.edit:
    path: /edit/{id}/
    defaults: { _controller: SmartBlogBundle:Article:edit }
    requirements:
        id: \d+

smart_blog.category.articles:
    path: /category/{slug}
    defaults:
        _controller: SmartBlogBundle:Category:articles
        slug: ""
    requirements:
        slug: ".+"

smart_blog_tag_index:
    path: /tag/
    defaults: { _controller: SmartBlogBundle:Tag:index }

smart_blog_tag:
    path: /tag/{slug}/
    defaults: { _controller: SmartBlogBundle:Tag:showArticles }

smart_blog_archive: # @todo
    path: /archive/
    defaults: { _controller: SmartBlogBundle:Article:archive }

smart_blog_archive_yearly: # @todo
    path: /archive/{year}/
    defaults: { _controller: SmartBlogBundle:Article:archiveYearly }
    requirements:
        year:  \d+

smart_blog_archive_monthly:
    path: /archive/{year}/{month}/
    defaults: { _controller: SmartBlogBundle:Article:archiveMonthly }
    requirements:
        year:  \d+
        month: \d+

smart_blog_archive_daily: # @todo
    path: /archive/{year}/{month}/{day}/
    defaults: { _controller: SmartBlogBundle:Article:archiveDaily }
    requirements:
        year:  \d+
        month: \d+
        day:   \d+
