smart_blog_index:
    path: /
    defaults: { _controller: SmartBlogBundle:Article:page }

smart_blog_article:
    path: /{slug}.html
    defaults: { _controller: SmartBlogBundle:Article:show }

smart_blog_article_create:
    path: /create/
    defaults: { _controller: SmartBlogBundle:Article:create }

smart_blog_article_edit:
    path: /edit/{id}/
    defaults: { _controller: SmartBlogBundle:Article:edit }
    requirements:
        id: \d+

smart_blog_page_index:
    path: /page/
    defaults: { _controller: SmartBlogBundle:Article:page }

smart_blog_page:
    path: /page/{page}/
    defaults: { _controller: SmartBlogBundle:Article:page }

smart_blog_category:
    path: /category/{slug}/
    defaults:
        _controller: SmartBlogBundle:Category:index
        slug: ""
    requirements:
        slug: ".+"

smart_blog_tag_index:
    path: /tag/
    defaults: { _controller: SmartBlogBundle:Tag:index }

smart_blog_tag:
    path: /tag/{slug}/
    defaults: { _controller: SmartBlogBundle:Tag:showArticles }

smart_blog_archive:
    path: /archive/
    defaults: { _controller: SmartBlogBundle:Article:archive }

smart_blog_archive_yearly: # @todo
    path: /archive/{year}/
    defaults: { _controller: SmartBlogBundle:Article:archiveYearly }
    requirements:
        year:  \d+

smart_blog_archive_monthly:
    path: /archive/{year}/{month}/
    defaults: { _controller: SmartBlogBundle:Article:archiveMonthly }
    requirements:
        year:  \d+
        month: \d+

smart_blog_archive_dayly: # @todo
    path: /archive/{year}/{month}/{day}/
    defaults: { _controller: SmartBlogBundle:Article:archiveDayly }
    requirements:
        year:  \d+
        month: \d+
        day:   \d+

#smart_blog_admin:
#    resource: "@SmartBlogBundle/Resources/config/routing_admin.yml"
#    prefix: /admin/
