services:
    smart_blog.article:
        class: SmartCore\Bundle\BlogBundle\Service\ArticleService
        arguments:
            - @doctrine.orm.default_entity_manager
            - @smart_blog.article.repository
            - @smart_blog.cache
            - @event_dispatcher
            - %smart_blog.items_per_page%

    smart_blog.tag:
        class: SmartCore\Bundle\BlogBundle\Service\TagService
        arguments:
            - @doctrine.orm.default_entity_manager
            - @smart_blog.article.repository
            - @smart_blog.cache
            - @smart_blog.tag.repository
            - @event_dispatcher
            - @router
            - %smart_blog.items_per_page%

    smart_blog.category:
        class: SmartCore\Bundle\BlogBundle\Service\CategoryService
        arguments:
            - @doctrine.orm.default_entity_manager
            - @smart_blog.category.repository
            - @smart_blog.cache

    smart_blog.cache: # @todo настройку через конфиг.
        alias: liip_doctrine_cache.ns.smart_blog

    smart_blog.article.create.form.type:
        class: SmartCore\Bundle\BlogBundle\Form\Type\ArticleCreateFormType
        arguments: [%smart_blog.model.article.class%]

    smart_blog.article.edit.form.type:
        class: SmartCore\Bundle\BlogBundle\Form\Type\ArticleEditFormType
        arguments: [%smart_blog.model.article.class%]

    smart_blog.category.create.form.type:
        class: SmartCore\Bundle\BlogBundle\Form\Type\CategoryCreateFormType
        arguments: [%smart_blog.model.category.class%]

    smart_blog.category.edit.form.type:
        class: SmartCore\Bundle\BlogBundle\Form\Type\CategoryEditFormType
        arguments: [%smart_blog.model.category.class%]

    smart_blog.article.repository:
        class:           SmartCore\Bundle\BlogBundle\Repository\ArticleRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:       [%smart_blog.model.article.class%]

    smart_blog.tag.repository:
        class:           SmartCore\Bundle\BlogBundle\Repository\TagRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:       [%smart_blog.model.tag.class%]

    smart_blog.category.repository:
        class:           SmartCore\Bundle\BlogBundle\Repository\CategoryRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:       [%smart_blog.model.category.class%]
